name: Sync OpenAPI definition to ReadMe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd docs
          pip install -r requirements.txt

      - name: Generate OpenAPI specification
        run: |
          cd docs
          python generate_openapi.py

      - name: Sync OpenAPI to ReadMe
        uses: readmeio/rdme@v10
        with:
          rdme: openapi docs/openapi.json --key=${{ secrets.README_API_KEY }}
